eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8081
spring:
  application:
    name: gateway
zuul:
  routes:
    api:
      path: /yixlapi/**
      serviceId: eurekaclient